version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/envoy-proxy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker/auth-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker/web-echo"
    schedule:
      interval: "weekly"
