version: '2'
services:

  proxy:
    build:
      context: ./docker/envoy-proxy
      dockerfile: Dockerfile
    volumes:
      - ./docker/envoy-proxy/envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  web_echo:
    build:
      context: ./docker/web-echo
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - web_echo
    expose:
      - "80"
    ports:
      - "8080:80"

  auth_srv:
    build:
      context: ./docker/auth-service
      dockerfile: Dockerfile
    networks:
      - envoymesh


networks:
  envoymesh: {}
