version: '2'
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  web_echo:
    build:
      context: .
      dockerfile: Dockerfile-web-echo
    networks:
      envoymesh:
        aliases:
          - web_echo
    expose:
      - "80"
    ports:
      - "8080:80"

  auth_srv:
    build:
      context: .
      dockerfile: Dockerfile-auth-service
    networks:
      envoymesh:
        aliases:
          - auth_srv
    expose:
      - "3000"
    ports:
      - "3000:3000"


networks:
  envoymesh: {}
